#! /bin/sh

if test "$2" != compiling -a ! -f genincludes/flrtable.flh ; then
    echo ""
    echo "+++++ FLORA-2 must first be compiled with the makeflora command"
    echo ""
    exit 1
fi

if test "$1" = none -o -z "$1" ; then
   PROLOG=`which xsb`
else
   PROLOG=$1
fi

if [ -z "$PROLOG" ] ; then
    echo ""
    echo "+++++ Usage:"
    if [ -n "$2" ] ; then
	echo "+++++   makeflora all path-for-/XSB/bin/xsb"
    else
	echo "+++++   floraconfig path-for-/XSB/bin/xsb"
    fi
    echo ""
    exit 1
else
    echo ""
    echo "+++++ Using prolog engine: $PROLOG"
    echo ""
fi

# Generate the files that contain the Prolog & Flora installation directories
# Generates runflora file that can be used to run flora
(echo "[flrdepstest]." | $PROLOG) || xsbinstallerror=true
if test -n "$xsbinstallerror" ; then
    echo ""
    echo "+++++ XSB is not configured or its sources have not been installed"
    echo ""
    exit 1
fi

(echo "['flrconfig']." | $PROLOG) || florausageerror=true
if test -n "$florausageerror" ; then
    echo ""
    echo "+++++ Usage:"
    echo "+++++   floraconfig path-for-/XSB/bin/xsb"
    echo ""
    exit 1
fi
