#! /bin/sh

if test ! "$*" = ""; then
    extra_args="$*"
fi

. .flora_paths

#PROLOGOPTIONS="-m 2000000 -c 50000"
#PROLOGOPTIONS="-p -m 2000000 -c 50000"
#PROLOGOPTIONS="-p"
#PROFILING="xsb_profiling:profile_unindexed_calls(on)."

$PROLOG $PROLOGOPTIONS -e "$PROFILING asserta(library_directory($FLORADIR)). [flora2]. flora_shell." $extra_args
