#! /bin/sh

if test "$1" = "--devel"; then
    STARTUPOPTIONS=""
    shift
else
    STARTUPOPTIONS="--noprompt --quietload --nofeedback --nobanner"
fi

if test ! "$*" = ""; then
    extra_args="$*"
fi

thisdir=`dirname $0`
. $thisdir/.flora_paths

#PROLOGOPTIONS="-m 2000000 -c 50000"
#PROLOGOPTIONS="-p -m 2000000 -c 50000"
#PROLOGOPTIONS="-p"
#PROFILING="xsb_profiling:profile_unindexed_calls(once)."

"$PROLOG" $STARTUPOPTIONS $PROLOGOPTIONS -e "$PROFILING asserta(library_directory($FLORADIR)). [flora2]. flora_shell." $extra_args
