#! /bin/sh

if [ "`basename $0`" = runergo ] ; then
    flrshell=ergo_shell
else
    flrshell=flora_shell
fi

if test "$1" = "--devel"; then
    STARTUPOPTIONS=""
    shift
else
    STARTUPOPTIONS="--noprompt --quietload --nofeedback --nobanner"
fi

if test ! "$*" = ""; then
    extra_args="$*"
fi

# If readlink exists - use it
thisscript=`(readlink -f "$0") 2> /dev/null || (readlink "$0") 2> /dev/null || echo "$0"`
thisdir=`dirname "$thisscript"`
#thisdir=`dirname "$0"`
. "$thisdir/.flora_paths"

#PROLOGOPTIONS="-m 8000000 -c 12000000"
#PROLOGOPTIONS="-m 4000000 -c 12000000"
#PROLOGOPTIONS="-m 2000000 -c 50000"

#PROFILEFLAG="-p"
#PROFILEINDEX="xsb_profiling:profile_unindexed_calls(once)."

"$PROLOG" $STARTUPOPTIONS $PROLOGOPTIONS $PROFILEFLAG -e "$PROFILEINDEX asserta(library_directory($FLORADIR)). [flora2]. $flrshell." $extra_args
