#! /bin/sh

if test "$1" = "" ; then
   PROLOG=xsb
else
   PROLOG=$1
fi

# Generate the files that contain the Prolog & Flora installation directories
# Generates runflora file that can be used to run flora
rm -fr .makeflora.tmp
(echo "['flrdepstest']." | $PROLOG) \
    || (echo "++Please reconfigure or reinstall XSB.";  touch .makeflora.tmp)
if test -f .makeflora.tmp ; then
    rm -rf .makeflora.tmp
    exit 1
fi

(echo "['flrconfig']." | $PROLOG) \
    || (echo "Usage:  makeflora all full-path-to-prolog"; touch .makeflora.tmp)
if test -f .makeflora.tmp ; then
    rm -rf .makeflora.tmp
    exit 1
fi
