#! /bin/sh

if test "$1" = "" ; then
   PROLOG=xsb
else
   PROLOG=$1
fi

# Generate the files that contain the Prolog & Flora installation directories
# Generates runflora file that can be used to run flora
(echo "[flrdepstest]." | $PROLOG) || error=true
if test -n "$error" ; then
    echo ""
    echo "+++++ XSB is not configured or its sources have not been installed"
    echo ""
    exit 1
fi

if test "$2" != compiling -a ! -f genincludes/flrtable.flh ; then
    echo ""
    echo "+++++ FLORA-2 must be first compiled with the makeflora command"
    echo ""
    exit 1
fi

(echo "['flrconfig']." | $PROLOG) || error=true
if test -n "$error" ; then
    echo ""
    echo "++++ Usage:  setflora full-path-to-prolog"
    echo ""
    exit 1
fi
