## File:      flora2/emacs/Makefile
##
## Author(s): Michael Kifer
##
## Contact:   kifer@cs.stonybrook.edu
##
## Copyright (C) by
##      The Research Foundation of the State University of New York, 1999-2008.
##
## All rights reserved.
##
## For information about licensing terms, please see
## http://silk.projects.semwebcentral.org/flora2-license.html
##
##



clean:
	/bin/rm -f *.bak *~ .*~ .#*

veryclean: clean
	/bin/rm -f *.elc
